# Generated by Django 2.1.5 on 2019-01-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='code',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Author1', max_length=100),
            preserve_default=False,
        ),
    ]
